### PR TITLE
added piwik ecommerce tracking events

### PR DESCRIPTION
**Pull request by silvan88**
We're using Piwik in our Angular webshop. In order to use ecommerce tracking, some additional tracking events needed to be implemented. I've added them to the plugin so that other people can use this as well. It would be nice if this can be integrated into the angulartics-piwik codebase so that everybody can benefit from future improvements.

### CODE REVIEW

**Comment by ienemien** [comment]
I need this functionality too, can you please merge this pull request?

**Comment by Chillian** [comment]
I would like to see this functionality as well

**Comment by geertjanb** [comment]
i need this as well, please merge :)

**Comment by Jannemannetje** [comment]
I was looking for a solution like this for a while now, please merge!

**Comment by Edalbrelord** [comment]
It would be nice to see the angulartics module supporting all events Piwik can handle. This looks like a step in the right direction.

**Comment by michelj90** [comment]
It would be really nice if we have the possibility to send e-commerce data to Piwik.

Please merge :pray:

**Comment by vdriet** [comment]
+1 for this request, I like to have this soon

**Comment by melletron** [comment]
+1

**Comment by inolasco** [comment]
Sorry for the delay, merged and updated bower and npm with v1.0.6

**Comment by silvan88** [comment]
No worries, thanks for merging :)

**Pull request merged**
